/* 由 tools/make_audio.py 自動產生，請勿手動修改 */
window.AUDIO = {
"Alex|Ryan, do you have a minute? I'm still trying to figure out who does what on the team.": "audio/alex-391f0e0c1ef9.mp3",
"Ryan|Sure. Emma leads the team, and she's the one who sets our priorities.": "audio/ryan-6a9fdf6124d2.mp3",
"Alex|Got it. And who should I talk to about the data pipeline?": "audio/alex-8689c4544566.mp3",
"Ryan|That's me. I'm in charge of the data pipeline, so I'm your go-to person for anything technical.": "audio/ryan-924c4c5f8490.mp3",
"Alex|Great. What about the planning team? I'll probably work closely with them.": "audio/alex-c5813caef4ae.mp3",
"Ryan|Emily is your main contact there. I'll add you to their group chat after lunch.": "audio/ryan-59495bf2f6d8.mp3",
"Ryan|So the QBR deck needs the new numbers by Thursday, and we'll sync with sales after that.": "audio/ryan-09e9f43229c2.mp3",
"Alex|Sorry, I didn't catch that. Could you tell me what QBR stands for?": "audio/alex-f1c770f2bacf.mp3",
"Ryan|Oh, sorry. It's the Quarterly Business Review. We present it to management every quarter.": "audio/ryan-c03799943c03.mp3",
"Alex|Thanks. So, just to make sure I understand: you need the updated numbers in the deck by Thursday?": "audio/alex-aa9f41def221.mp3",
"Emma|Exactly. Ryan can go over the format with you after the meeting.": "audio/emma-71e435de8365.mp3",
"Alex|Perfect. I'll have it ready by Wednesday so we have time to review.": "audio/alex-2b8cf7b7ab37.mp3",
"Ryan|Hey Alex, how's it going?": "audio/ryan-12b0570610a9.mp3",
"Alex|Pretty good, thanks! Busy, but in a good way. How about you?": "audio/alex-be2dcba20f4d.mp3",
"Ryan|Not bad. Just trying to survive Monday.": "audio/ryan-c3368103e6ab.mp3",
"Emma|Morning, Alex. So, how's your onboarding going so far?": "audio/emma-771de7d054fd.mp3",
"Alex|It's going well. Everyone's been really helpful. I'm still getting used to all the tools, though.": "audio/alex-f9f7cc2f25eb.mp3",
"Emma|That's totally normal. Let me know if anything's unclear.": "audio/emma-40fa9d250c67.mp3",
"Alex|Will do. Thanks, Emma!": "audio/alex-ce6016ec4fec.mp3",
"Ryan|Morning, Alex! How was your weekend?": "audio/ryan-693c0fc53849.mp3",
"Alex|Pretty good, thanks. I finally tried that ramen place near the station. Have you ever been there?": "audio/alex-0be0251e42c2.mp3",
"Ryan|Yes! I go there all the time. Did you try the spicy one?": "audio/ryan-9784e100359a.mp3",
"Alex|I did. It was amazing. How about you? Did you do anything fun?": "audio/alex-fb12a3afe815.mp3",
"Ryan|Not much. I just stayed home and caught up on some shows.": "audio/ryan-dd0bb68bc5d0.mp3",
"Alex|Sounds relaxing. We should grab lunch there sometime.": "audio/alex-e759f0e7bb05.mp3",
"Alex|Emma, I was wondering if I could get your input on something.": "audio/alex-49adab779c0c.mp3",
"Emma|Of course. What's going on?": "audio/emma-608d590b9c14.mp3",
"Alex|I'm stuck on the customer analysis. The data from two systems doesn't match, and I'm not sure which one to use.": "audio/alex-1d40781b8448.mp3",
"Emma|Good question. In general, we treat the sales system as the source of truth.": "audio/emma-3ca7a939c749.mp3",
"Alex|That helps. Would you mind taking a look at my approach before I go further?": "audio/alex-08bb5528da28.mp3",
"Emma|Not at all. Send it over and I'll review it this afternoon.": "audio/emma-6eaa8340b486.mp3",
"Emma|Let's talk about your goals for this quarter. What would you like to achieve?": "audio/emma-2be1897aa35e.mp3",
"Alex|By the end of the quarter, I'd like to have the weekly report fully automated.": "audio/alex-7cd49ecb5d2e.mp3",
"Emma|I like that. How will we know it's working?": "audio/emma-f66372cc1f3c.mp3",
"Alex|The report should take less than 30 minutes a week, instead of half a day.": "audio/alex-33f6d044bc91.mp3",
"Emma|That's clear and measurable. What do you need from me?": "audio/emma-f740fccab203.mp3",
"Alex|Mainly access to the finance data. I'll share a milestone plan by Friday.": "audio/alex-b841fdf6f523.mp3",
"Emma|I read your report. The analysis is solid, but I have a bit of feedback.": "audio/emma-1bf4ea52a877.mp3",
"Alex|Sure, please go ahead.": "audio/alex-341e9e370468.mp3",
"Emma|The key findings are on page five. Most people won't read that far.": "audio/emma-ee04b670d3d6.mp3",
"Alex|That makes sense. I should have put the summary on the first page.": "audio/alex-6897390f6b1b.mp3",
"Emma|Exactly. Also, a few charts don't have labels, so they're hard to read.": "audio/emma-7a02c326250e.mp3",
"Alex|Thanks for pointing that out. Moving forward, I'll add a one-page summary and check every chart.": "audio/alex-b33df689b734.mp3",
"Alex|Before we wrap up, I've been thinking about how we share reports with the planning team.": "audio/alex-59727e1bfe36.mp3",
"Emma|Oh? What do you have in mind?": "audio/emma-843075c00ac8.mp3",
"Alex|Instead of emailing files every week, we could build a shared dashboard. It would save everyone time.": "audio/alex-765c8e1a0510.mp3",
"Emma|Interesting. Could you put together a short proposal?": "audio/emma-105cb3bf1623.mp3",
"Alex|Sure. Also, in the long run, I'm interested in taking on more project management work.": "audio/alex-51398a334861.mp3",
"Emma|Good to know. This dashboard could be a great first project for you to lead.": "audio/emma-7ceb645543a3.mp3",
"Ryan|And if we move the launch, marketing will need to redo all the materials, and sales will...": "audio/ryan-04d51424857d.mp3",
"Alex|Sorry to jump in, Ryan. Can I add something here?": "audio/alex-0a4bd93ec32c.mp3",
"Ryan|Sure, go ahead.": "audio/ryan-e9143d8b3e0a.mp3",
"Alex|I checked last year's data. When we delayed a launch by two weeks, sales only dropped by 2%.": "audio/alex-37e17bc21ad6.mp3",
"Emily|But this year is different, because...": "audio/emily-29f572133b3e.mp3",
"Alex|Sorry, Emily, let me just finish my point. So a short delay might be less risky than we think.": "audio/alex-cdae2972e200.mp3",
"Emma|Good point, Alex. Emily, what were you going to say?": "audio/emma-14ae7fa00d1b.mp3",
"Emma|Alex, can you give us an update on the dashboard?": "audio/emma-8398132e16cf.mp3",
"Alex|Sure. So far, we're about 70% done. The data connection has been completed, and the main charts have been built.": "audio/alex-2fef63433952.mp3",
"Ryan|Nice. What's left?": "audio/ryan-92f2220ec9bc.mp3",
"Alex|The remaining work is the filters and user testing. We're actually a little ahead of schedule.": "audio/alex-84f66035cb43.mp3",
"Emma|Great. When do you estimate it'll be ready?": "audio/emma-c58889bfc235.mp3",
"Alex|We should be able to launch by the 20th, assuming testing goes smoothly.": "audio/alex-12e72eafc84b.mp3",
"Emma|Alex, what was our customer retention rate last quarter?": "audio/emma-f61d03bacfad.mp3",
"Alex|Good question. I don't have the exact number off the top of my head.": "audio/alex-8ec586253563.mp3",
"Alex|I believe it was around 80%, but I'd like to double-check before I confirm.": "audio/alex-7e2144eacfc6.mp3",
"Emma|Sure. When can you get back to me?": "audio/emma-a80d71c79b93.mp3",
"Alex|I'll check the dashboard after the meeting and send it to you by 3 p.m.": "audio/alex-977b242756b3.mp3",
"Ryan|The finance team has that report too, if that helps.": "audio/ryan-a1098a38424c.mp3",
"Alex|Thanks, Ryan. I'll reach out to them as well.": "audio/alex-9976dab0a1dd.mp3",
"Ryan|I think we should send an automatic reminder when the new report is ready.": "audio/ryan-adcd1f33bdba.mp3",
"Alex|I agree with Ryan. That's a really good point.": "audio/alex-d97a5254037e.mp3",
"Alex|To build on that, we could include the three key numbers in the reminder itself.": "audio/alex-6269ddd45dbf.mp3",
"Emma|Why is that better?": "audio/emma-8733e72d066b.mp3",
"Alex|Most people only need the headline numbers. On top of that, it'd encourage them to open the full report.": "audio/alex-b08fba2e0e87.mp3",
"Ryan|I couldn't agree more. I can set that up next week.": "audio/ryan-dfebd34ada6f.mp3",
"Ryan|The new system is ready. I suggest we launch it next Monday.": "audio/ryan-677b6e3ea546.mp3",
"Alex|I see your point, and I know everyone wants it out soon. But I'm not sure next Monday is realistic.": "audio/alex-4dc7e8ea521d.mp3",
"Ryan|Why do you think so?": "audio/ryan-c6337358128d.mp3",
"Alex|Although the system works, the sales team hasn't had any training yet. They might struggle on day one.": "audio/alex-a93c1b762b85.mp3",
"Emma|That's a fair concern. What would you suggest?": "audio/emma-cc6befb405ca.mp3",
"Alex|What if we run a training session this week and launch the following Monday instead?": "audio/alex-0a99ff8c0b68.mp3",
"Emma|Can you explain what happened with the dashboard this morning?": "audio/emma-ce793dbcbc04.mp3",
"Alex|Sure. The dashboard went down at 8 a.m. due to a data loading error.": "audio/alex-4889e14378df.mp3",
"Ryan|We looked into it, and it turned out that a database update changed one of the column names.": "audio/ryan-b5d243b070c1.mp3",
"Alex|Because the column name changed, our script couldn't find the data. That's the root cause.": "audio/alex-61309694e27d.mp3",
"Emma|I see. Is it fixed now?": "audio/emma-72942cc4f40a.mp3",
"Alex|Yes, it's been back up since 11. To prevent this in the future, we'll get notified before any database changes.": "audio/alex-ab14af8ff2ab.mp3",
"Alex|Our supplier is raising prices by 10% next month. I've looked at a few options.": "audio/alex-60624514c044.mp3",
"Emma|Okay, what are they?": "audio/emma-f1471bf23c98.mp3",
"Alex|Option A: we accept the increase. It's the easiest, but our costs go up. Option B: we switch to a new supplier. It's cheaper, but it'll take about two months.": "audio/alex-302c754175ad.mp3",
"Alex|Option C: we negotiate a longer contract in exchange for a smaller increase.": "audio/alex-d767bd09ed47.mp3",
"Emma|Which one would you recommend?": "audio/emma-a3174ec45fdc.mp3",
"Alex|I'd go with Option C. It's less risky than switching suppliers, and it keeps costs lower than Option A.": "audio/alex-115b79ac0fed.mp3",
"Emma|Before we commit to the launch date, what are the main risks?": "audio/emma-386f9491f972.mp3",
"Alex|I see two. First, the payment system might not handle the extra traffic on launch day.": "audio/alex-d7998e1baa41.mp3",
"Ryan|That's possible. We could run a load test this week to check.": "audio/ryan-e76c1ddb190e.mp3",
"Alex|Second, the marketing materials may not be ready in time. That's less likely, but the impact would be big.": "audio/alex-2e755ed3e5e6.mp3",
"Emma|What's the worst-case scenario?": "audio/emma-07657d2a7ab7.mp3",
"Alex|Worst case, we delay the launch by a week. To be on the safe side, I'd prepare a backup plan.": "audio/alex-55dcb01f8780.mp3",
"Emily|Hi Alex, could we get the market report by Wednesday?": "audio/emily-81241a1c8505.mp3",
"Alex|I'd love to help, but Wednesday is going to be tight. I'm also finishing the quarterly review this week.": "audio/alex-2a4c08761726.mp3",
"Emily|I see. When do you think is realistic?": "audio/emily-c72691e21cb8.mp3",
"Alex|If I had until Friday, I could include the latest sales data as well.": "audio/alex-25756bbdf6b6.mp3",
"Emily|Friday is a bit late for us. Could you send part of it earlier?": "audio/emily-00118ee996e1.mp3",
"Alex|How about this: I'll send the key charts on Wednesday and the full report on Friday. Would that work?": "audio/alex-3c794f67245f.mp3",
"Alex|Hi Emily, do you have a few minutes? I need some help from your team on the new feature.": "audio/alex-28559732b732.mp3",
"Emily|Sure. What do you need?": "audio/emily-70ee481e291a.mp3",
"Alex|We need someone to prepare the product forecast so that we can test the feature with real numbers.": "audio/alex-fd421113f207.mp3",
"Emily|I see. Honestly, we don't have much bandwidth this month. How much time would it take?": "audio/emily-7e0d7d12c6fe.mp3",
"Alex|About two days of work. I know it's short notice, so I can help clean up the data on my side.": "audio/alex-fdb62db60f83.mp3",
"Emily|That helps. Let me check with my manager and see if we can free up someone next week.": "audio/emily-9f4a6d3e1f5f.mp3",
"Alex|Hi Emily, I just wanted to check in on the forecast data. Any updates?": "audio/alex-4df8701ad92a.mp3",
"Emily|Oh, sorry! It's been a crazy week. It's almost done.": "audio/emily-0f9270d88066.mp3",
"Alex|No worries. Do you have an ETA? We're planning to start testing on Thursday.": "audio/alex-ff9b833494f7.mp3",
"Emily|I can send it by end of day tomorrow.": "audio/emily-a58e03978885.mp3",
"Alex|That works. If anything comes up, just let me know and we can adjust.": "audio/alex-a67544fb8a05.mp3",
"Emily|Will do. Thanks for being so patient.": "audio/emily-9667efdfdf43.mp3",
"Alex|Before I start, I'd like to make sure we're on the same page about the report.": "audio/alex-fe295568eb71.mp3",
"Emily|Good idea. What would you like to check?": "audio/emily-9054e3b598aa.mp3",
"Alex|In terms of format, is a slide deck okay, or are you expecting an Excel file?": "audio/alex-1a8c2e7fede1.mp3",
"Emily|A deck is fine. It's supposed to go to our director, so it should be short.": "audio/emily-a5a4b464fbe2.mp3",
"Alex|Got it. So the deliverable is a five-page deck with the main trends, due next Friday. Is that right?": "audio/alex-424719807779.mp3",
"Emily|Perfect. That's exactly what we need.": "audio/emily-6cbb57b8dd71.mp3",
"Ryan|We need to fix the bugs first. If we add new features now, the system will get even less stable.": "audio/ryan-eb5bf942a6dc.mp3",
"Emily|But our customers are waiting for the new features. We promised them by next month.": "audio/emily-ee15a8c59807.mp3",
"Alex|Let's take a step back. It sounds like we both want happy customers, right?": "audio/alex-96c8801e1398.mp3",
"Ryan|Of course.": "audio/ryan-f282438aa1bc.mp3",
"Alex|How about fixing the three critical bugs first, and then releasing the most requested feature?": "audio/alex-83c6fa0ddd4b.mp3",
"Emily|That's a fair compromise. I can explain the new timing to the customers.": "audio/emily-80f2a64fc33e.mp3",
"Alex|Let's split up the work for the dashboard project. Ryan, could you take care of the data connection?": "audio/alex-a83574b329e5.mp3",
"Ryan|Sure. When do you need it by?": "audio/ryan-fbd53ede3d9e.mp3",
"Alex|Ideally by the 15th. Emily, could you own the requirements and get feedback from your team?": "audio/alex-a306e2432b1e.mp3",
"Emily|Happy to. I'll have my team review the draft this week.": "audio/emily-fe27c205bf4a.mp3",
"Alex|Great. I'll handle the design and the overall timeline. Let's keep each other posted in the project channel.": "audio/alex-5e7a390552dc.mp3",
"Ryan|Sounds like a plan.": "audio/ryan-61b0e7f1acb6.mp3",
"Emma|We're almost out of time. Alex, could you sum up?": "audio/emma-b79b78960fd5.mp3",
"Alex|Sure. To sum up, we decided to launch on May 20th.": "audio/alex-87b84b10b706.mp3",
"Alex|For action items: Ryan is going to finish the load test by Friday, and I'm going to update the launch plan.": "audio/alex-288d73b36216.mp3",
"Ryan|And I'll share the test results in the channel.": "audio/ryan-3b6999f0274e.mp3",
"Alex|Great. One open question is the marketing budget. We'll follow up on that next week.": "audio/alex-2f14a66c9092.mp3",
"Emma|Perfect. Please send the meeting notes to everyone today.": "audio/emma-f48e9596cddf.mp3",
"Alex|Ryan, could you look over my follow-up email before I send it?": "audio/alex-78b2a9727190.mp3",
"Ryan|Sure. Read me the opening.": "audio/ryan-9efce194295d.mp3",
"Alex|Hi all, thanks for your time today. I'm writing to recap what we discussed and confirm next steps.": "audio/alex-f636288782f4.mp3",
"Ryan|Nice and clear. Did you attach the slides?": "audio/ryan-21dc2f3fa5fb.mp3",
"Alex|Yes. I wrote: Please find the slides attached. Then I listed each action item with an owner and a date.": "audio/alex-364e6930900c.mp3",
"Ryan|Perfect. Maybe end with: Please let me know if I missed anything.": "audio/ryan-c5bee491fce0.mp3",
"Emma|Alex, can you hear me? I think you're on mute.": "audio/emma-7d5d9350a8db.mp3",
"Alex|Sorry about that! Can you hear me now?": "audio/alex-f26c2d0d1d01.mp3",
"Ryan|Yes, but you're breaking up a little. Your video is freezing too.": "audio/ryan-0507b08195b0.mp3",
"Alex|Let me turn off my camera. Is that better?": "audio/alex-0b2151504434.mp3",
"Emma|Much better. Could you share your screen?": "audio/emma-d3d39176bb15.mp3",
"Alex|Sure. Can everyone see my screen? If I drop off, I'll call back in right away.": "audio/alex-bc73c8ee8076.mp3",
"Emma|Alex, why don't you start with the dashboard project?": "audio/emma-afd520954ca7.mp3",
"Alex|Sure. Overall, we're on track. The data connection has been completed, and user testing starts next week.": "audio/alex-545a54b230ff.mp3",
"Alex|One issue: the planning data is arriving late due to a system change. If it's late again, we'll miss the test date.": "audio/alex-39f759a04963.mp3",
"Emily|Sorry about that. We're fixing it on our side.": "audio/emily-f4f42dcad360.mp3",
"Alex|No problem. I'd suggest we use last month's data for the first round of testing. It's less accurate, but it keeps us on schedule.": "audio/alex-fff30b266579.mp3",
"Ryan|I agree. On top of that, it gives us time to test the system itself.": "audio/ryan-88685533f2b4.mp3",
"Emma|Okay, let's go with that. Alex, can you wrap up?": "audio/emma-b4aa4ca1fb3f.mp3",
"Alex|To sum up, we'll test with last month's data, and Emily will send the new data by Friday. I'll send a recap email today.": "audio/alex-6ca749a793ef.mp3",
"Emma|Good morning, everyone. I'd like you to meet the newest member of our team.": "audio/emma-4dc502531b30.mp3",
"Alex|Hi, I'm Alex. Nice to meet you all. I'm joining the team as an analyst.": "audio/alex-15e3e306783b.mp3",
"Ryan|Welcome aboard, Alex! What were you doing before this?": "audio/ryan-ffd39ee80649.mp3",
"Alex|I was a data analyst at a marketing agency. I'm looking forward to getting up to speed on our products.": "audio/alex-5d853f64c84a.mp3",
"Ryan|Great. Feel free to reach out if you need anything.": "audio/ryan-a6abc627324d.mp3",
"Alex|Thanks, I really appreciate it.": "audio/alex-a2e77dd28a31.mp3",
"Emma|So, how's the forecast report going?": "audio/emma-9d3e75f9fa75.mp3",
"Alex|Overall, it's on track. The final version will be ready by Friday.": "audio/alex-279eee0ec022.mp3",
"Emma|Great. Where are you at right now?": "audio/emma-bbec96711880.mp3",
"Alex|I've finished the first draft, but I haven't received the latest data from the planning team yet.": "audio/alex-e25ded6a610a.mp3",
"Emma|Do you want me to reach out to them?": "audio/emma-39b56a04e029.mp3",
"Alex|That would help a lot. Then I can wrap it up by Thursday.": "audio/alex-a9da06ebaa75.mp3",
"Alex|I have an update on the shipment. Unfortunately, it's going to be delayed by about a week.": "audio/alex-95153f8a9090.mp3",
"Ryan|A week? What happened?": "audio/ryan-369bf8aded1b.mp3",
"Alex|The supplier found a quality issue, so they need to rework some parts.": "audio/alex-72e492da3e84.mp3",
"Emma|How will this affect the test schedule?": "audio/emma-e826c3ab97b2.mp3",
"Alex|If nothing changes, we'll miss the test date. I'd suggest we split the shipment, but I'll need support from the logistics team.": "audio/alex-a34bc9943fd1.mp3",
"Emma|Makes sense. I'll talk to their manager today.": "audio/emma-038db10716a1.mp3",
"Alex|Let me walk you through the numbers. Total orders dropped by 15% last month.": "audio/alex-3ef3154c8ac2.mp3",
"Emma|That's a big drop. Do we know why?": "audio/emma-67f29e6bd5cb.mp3",
"Alex|When we break it down by region, most of the decline came from Europe.": "audio/alex-8cf1da8091a2.mp3",
"Ryan|Is it a trend, or a one-time thing?": "audio/ryan-cf4f03408b90.mp3",
"Alex|It looks like a one-time thing. One major customer moved their order to next quarter.": "audio/alex-7948f35f1c25.mp3",
"Emma|Okay. Let's keep an eye on it next month.": "audio/emma-e1021b36db56.mp3",
"Emily|Hi! I don't think we've met. I'm Emily from planning.": "audio/emily-6f5f657a51b3.mp3",
"Alex|Nice to meet you, Emily. I'm Alex. I just joined the analytics team this week.": "audio/alex-f5ec6066ed9f.mp3",
"Emily|Oh, welcome! I'm sure we'll be working together a lot.": "audio/emily-5cc2980b7a13.mp3",
"Alex|I'm looking forward to it. See you around!": "audio/alex-353a55475df0.mp3",
"Alex|Hey Ryan, do you have a sec?": "audio/alex-b3f65b3a8ed5.mp3",
"Ryan|Sure, what's up?": "audio/ryan-5a3fdf677c51.mp3",
"Alex|Just a quick question about the report. It'll only take a minute.": "audio/alex-fe1bf19ccc56.mp3",
"Ryan|So we'll need the numbers by Thursday and the deck by Friday morning, and then...": "audio/ryan-67789a542503.mp3",
"Alex|Sorry, could you slow down a little? I want to make sure I get everything.": "audio/alex-267c4a3c8eb4.mp3",
"Ryan|Oh, sure. Numbers by Thursday, deck by Friday morning.": "audio/ryan-0941a40510e6.mp3",
"Alex|Sorry, I missed the last part. Could you repeat that?": "audio/alex-d7249919781f.mp3",
"Emma|No problem. I said we'll meet again next Tuesday.": "audio/emma-cc68eb67e213.mp3",
"Alex|Quick question. How do I get access to the sales database?": "audio/alex-8ea3caefa306.mp3",
"Ryan|Submit a request through the IT portal. Emma has to approve it.": "audio/ryan-a52008216d57.mp3",
"Alex|Got it. Is there a template for the weekly report too?": "audio/alex-90e9bd6049b3.mp3",
"Ryan|Yes, it's on the shared drive. I'll send you the link.": "audio/ryan-7ce8a24612e4.mp3",
"Ryan|Any plans for the weekend?": "audio/ryan-0a56c54ba1fd.mp3",
"Alex|Nothing special. Probably just catching up on sleep! You?": "audio/alex-8e611e541353.mp3",
"Ryan|I'm going hiking if the weather's nice.": "audio/ryan-a4812ac5a11b.mp3",
"Alex|Sounds fun. Have a good weekend!": "audio/alex-6930b4ac776b.mp3",
"Emily|Alex! Long time no see. How have you been?": "audio/emily-64e002cbeb78.mp3",
"Alex|I've been good, just really busy with the new project. How about you?": "audio/alex-dd0b73411379.mp3",
"Emma|Before we wrap up, are there any major blockers?": "audio/emma-730a5dc26547.mp3",
"Alex|Nothing major right now. One small thing, though: I'm still waiting for access to the finance data.": "audio/alex-9c7a028e74d1.mp3",
"Emma|Okay, I'll follow up on that today.": "audio/emma-cd6bcc8bf77e.mp3",
"Ryan|Hey Alex, got a minute?": "audio/ryan-ac931f52212d.mp3",
"Alex|I'm in the middle of something. Can I get back to you in ten minutes?": "audio/alex-4ccaa3f9fc82.mp3",
"Ryan|Sure, no rush.": "audio/ryan-425d1326f634.mp3",
"Emma|Any questions for me?": "audio/emma-999afaa4a38d.mp3",
"Alex|Actually, yes. What does success look like for this role in six months?": "audio/alex-9ae52682266d.mp3",
"Emma|Great question. Let's talk about that.": "audio/emma-42f4d9b85db1.mp3",
"Emma|Great job on the presentation today, Alex.": "audio/emma-4fb429a2dd42.mp3",
"Alex|Thanks, I really appreciate that! Ryan helped me a lot with the data.": "audio/alex-7e73f4cdbbc4.mp3",
"Emma|How are you feeling about your workload?": "audio/emma-b5fe38949d35.mp3",
"Alex|Honestly, it's a bit much this week. Could we look at my priorities together?": "audio/alex-527a678cc537.mp3",
"Emma|Of course. Let's see what can wait.": "audio/emma-9859e81a9a59.mp3",
"Alex|Hi everyone, thanks for joining. Let's get started. We're here to decide on the launch date, and we'll keep it to 30 minutes.": "audio/alex-9772c95f1238.mp3",
"Ryan|Sounds good.": "audio/ryan-7c184b94d604.mp3",
"Alex|Sorry I'm late. What did I miss?": "audio/alex-3d85221e7700.mp3",
"Emma|No worries. We just finished the budget part.": "audio/emma-d6946d329606.mp3",
"Emma|What are you working on this week?": "audio/emma-0c58c0b921b6.mp3",
"Alex|Mainly the dashboard. I'm also helping Emily with the forecast.": "audio/alex-d2d1c0cbe672.mp3",
"Alex|Sorry, just to be clear: what's the decision here?": "audio/alex-9fde01abd9b8.mp3",
"Emma|Good point. We're going with Option B.": "audio/emma-5ec0b80de49b.mp3",
"Emily|We'd like the forecast updated weekly instead of monthly.": "audio/emily-78805d55abf9.mp3",
"Alex|When you say weekly, do you mean every Monday?": "audio/alex-84bd08c287eb.mp3",
"Emily|Yes, Monday morning would be ideal.": "audio/emily-9227da8314c6.mp3",
"Ryan|Thanks for sending the file so quickly!": "audio/ryan-066817de4f5d.mp3",
"Alex|Anytime! Happy to help.": "audio/alex-526e6fd739a2.mp3",
"Alex|That's a great point, but I think it's a bit off topic. Maybe we can take it offline?": "audio/alex-66529b151bf6.mp3",
"Ryan|Good call. Let's talk after the meeting.": "audio/ryan-840aa6868167.mp3",
"Alex|Emma, I made a mistake in yesterday's report. One of the numbers was wrong.": "audio/alex-0ef03cbbf25d.mp3",
"Emma|Thanks for flagging it. What happened?": "audio/emma-474c1c8564f0.mp3",
"Alex|I used the old data by mistake. I've already fixed it and sent the updated version.": "audio/alex-ed15c3e5ae52.mp3",
"Emma|Alex, what do you think?": "audio/emma-d2140eb9f4e3.mp3",
"Alex|Sorry, could you repeat the question? I want to make sure I answer the right thing.": "audio/alex-fa0de5b66f10.mp3",
"Alex|Could we set up a quick call to discuss the timeline?": "audio/alex-f993e6241062.mp3",
"Emily|Sure. Does Thursday at 2 work for you?": "audio/emily-8bfd44daef84.mp3",
"Alex|That works. I'll send an invite.": "audio/alex-fb92afae3013.mp3",
"Alex|Thanks for your help on this, Emily. I couldn't have done it without you.": "audio/alex-251c14b42e62.mp3",
"Emily|My pleasure! Let me know if you need anything else.": "audio/emily-1258fe68b4e2.mp3",
"Alex|Sorry for the late reply! I was in meetings all morning.": "audio/alex-ecd904a9bd95.mp3",
"Emily|No worries. Did you get a chance to look at the file?": "audio/emily-f5f509a48cf6.mp3",
"Alex|Hi Emma, I'm not feeling well today, so I'll be working from home.": "audio/alex-58e8a66f1d06.mp3",
"Emma|Sorry to hear that. Take care, and rest if you need to.": "audio/emma-c548ffb0a83f.mp3",
"Alex|Sorry, I have a hard stop at 3. I need to drop off for another meeting.": "audio/alex-93da4e044cfd.mp3",
"Emma|No problem. We'll send you the notes.": "audio/emma-daae42bd4575.mp3",
"Alex|Sorry, I forgot to attach the file. Here it is!": "audio/alex-60dd17857627.mp3",
"Ryan|Happens to everyone!": "audio/ryan-afca5c721718.mp3",
"Alex|Sorry, Ryan, your audio is a bit muffled. Could you move closer to your mic?": "audio/alex-c131db2dfaf8.mp3",
"Ryan|Is this better?": "audio/ryan-6639985e2568.mp3",
"Alex|Much better, thanks.": "audio/alex-6dedf331fc95.mp3",
"Alex|There's some background noise. Could everyone mute when they're not speaking?": "audio/alex-0ba480cae6a8.mp3",
"Ryan|Sorry, that's me. Muting now.": "audio/ryan-4b43a8017192.mp3",
"Ryan|Today's my last day. It's been great working with you, Alex.": "audio/ryan-60fe18a23ae3.mp3",
"Alex|Same here. I've learned so much from you. Keep in touch!": "audio/alex-bb9e7296d2a7.mp3"
};
